// 避难所管理台 —— 前端脚本
function t(tab){
  document.querySelectorAll('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.tab===tab));
  document.querySelectorAll('.tabpage').forEach(s=>s.classList.toggle('active',s.id==='tab-'+tab));
}
function esc(s){return (s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function api(path,opt){const r=await fetch(path,opt);return r.json()}
function show(id,s,ok){const el=document.getElementById(id);if(!el)return;el.style.color=ok?'#7a9e7e':'#c47a8b';el.textContent=s;setTimeout(()=>el.textContent='',4000)}
function readAsDataURL(f){return new Promise(function(r){var fr=new FileReader();fr.onload=function(){r(fr.result)};fr.readAsDataURL(f)})}
function compressImage(file,maxW){maxW=maxW||1200;return new Promise(function(resolve,fail){var reader=new FileReader();reader.onload=function(e){var img=new Image();img.onload=function(){var w=img.width,h=img.height;if(w>maxW){h=Math.round(h*maxW/w);w=maxW}var c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',0.8))};img.onerror=fail;img.src=e.target.result};reader.readAsDataURL(file)})}
function nowStr(){var d=new Date();function p(n){return (n<10?'0':'')+n}return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())+' '+p(d.getHours())+':'+p(d.getMinutes())+':00'}

/* ---- 文章 ---- */
var collections=[];
async function load(){var d=await api('/api/posts');var el=document.getElementById('posts');el.innerHTML=d.posts.map(function(p){return '<div class="pitem"><span>'+esc(p.title)+' <span class="small">['+esc(p.categories||'无合集')+']</span></span><span style="display:flex;gap:8px;align-items:center"><button class="btn btn-ghost" onclick="openPost(\''+encodeURIComponent(p.file)+'\')">编辑</button><span class="x" onclick="delPost(\''+encodeURIComponent(p.file)+'\')">×</span></span></div>'}).join('')||'<div class="small" style="padding:8px 0">还没有文章</div>'}
function onFilesChanged(){var input=document.getElementById('up_folder');var md=Array.from(input.files||[]).find(function(f){return /\.md$/i.test(f.name)});if(md){document.getElementById('f_title').value=md.name.replace(/\.md$/i,'')}}
var colMeta=[];
async function loadCollections(){var d=await api('/api/collections');colMeta=d.collections||[];collections=d.names||colMeta.map(function(c){return c.name});if(collections)collections.forEach(function(n){if(!colMeta.some(function(c){return c.name===n}))colMeta.push({name:n,cover:'',desc:''})});renderColMenu();renderColls()}
function renderColls(){var el=document.getElementById('collist');el.innerHTML=colMeta.map(function(c,i){return '<div class="collrow"><div style="display:flex;gap:8px;align-items:center"><img class="coll-thumb" src="'+esc(c.cover||'')+'" onerror="this.style.opacity=0"><input value="'+esc(c.name||'')+'" placeholder="合集名" onchange="colMeta['+i+'].name=this.value"></div><input value="'+esc(c.desc||'')+'" placeholder="简介" onchange="colMeta['+i+'].desc=this.value" style="margin-top:8px"><div style="margin-top:8px;display:flex;gap:8px;align-items:center"><input value="'+esc(c.cover||'')+'" placeholder="封面 /images/…" onchange="colMeta['+i+'].cover=this.value"><button class="btn btn-ghost" onclick="upCollCover('+i+')">传封面</button><button class="btn btn-del" onclick="delColl('+i+')">删除</button></div></div>'}).join('')||'<div class="small" style="padding:8px 0">还没有合集</div>'}
function addColl(){colMeta.push({name:'',cover:'',desc:''});renderColls()}
function delColl(i){colMeta.splice(i,1);renderColls()}
function upCollCover(i){var input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=function(){var f=input.files[0];if(!f)return;compressImage(f).then(function(data){api('/api/img',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({file:f.name,album:'collections',data:data})}).then(function(d){colMeta[i].cover=d.src;renderColls()})})};input.click()}
async function saveColls(){await api('/api/collections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({collections:colMeta})});show('collStatus','已保存合集',true);loadCollections()}
function renderColMenu(){if(!document.getElementById('col_menu'))return;var saved=document.getElementById('f_catsave').value;var opts=[{v:'',t:'无合集'}].concat(collections.map(function(c){return {v:c,t:c}})).concat([{v:'__new__',t:'＋ 创建新合集'}]);document.getElementById('col_menu').innerHTML=opts.map(function(o){return '<div class="dd-item'+(o.v===saved?' sel':'')+'" onclick="pickCol(\''+esc(o.v)+'\',\''+esc(o.t)+'\')">'+esc(o.t)+'</div>'}).join('');if(saved){document.getElementById('f_collection').value=saved;document.getElementById('col_label').textContent=saved}else{document.getElementById('f_collection').value='';document.getElementById('col_label').textContent='无合集'}document.getElementById('f_newcol').style.display=document.getElementById('f_collection').value==='__new__'?'block':'none'}
function toggleDD(){var m=document.getElementById('col_menu');var dd=m.parentElement;var open=m.style.display==='block';m.style.display=open?'none':'block';dd.classList.toggle('open',!open)}
function pickCol(v,t){document.getElementById('f_collection').value=v;document.getElementById('col_label').textContent=t;document.getElementById('col_menu').style.display='none';document.getElementById('col_menu').parentElement.classList.remove('open');document.getElementById('f_newcol').style.display=v==='__new__'?'block':'none'}
function newPost(){document.getElementById('f_file').value='';document.getElementById('f_catsave').value='';document.getElementById('f_title').value='';document.getElementById('f_summary').value='';document.getElementById('f_content').value='';document.getElementById('f_newcolname').value='';document.getElementById('f_date').value=nowStr();document.getElementById('form_hd').textContent='发布新文章';document.getElementById('cancelEdit').style.display='none';document.getElementById('up_folder').value='';renderColMenu()}
function cancelEdit(){newPost()}
async function openPost(file){var d=await api('/api/post?file='+file);var sel=document.getElementById('f_collection');document.getElementById('f_file').value=d.file;document.getElementById('f_catsave').value=d.categories;document.getElementById('f_title').value=d.title;document.getElementById('f_summary').value=d.description||'';document.getElementById('f_content').value=d.content;document.getElementById('f_date').value=nowStr();document.getElementById('form_hd').textContent='正在编辑：'+d.title;document.getElementById('cancelEdit').style.display='inline-block';if(d.categories&&collections.indexOf(d.categories)<0)collections.push(d.categories);renderColMenu();sel.value=d.categories;document.getElementById('f_newcol').style.display=sel.value==='__new__'?'block':'none'}
async function readFolder(){var input=document.getElementById('up_folder');if(!input.files.length){show('upStatus','请选择文档文件夹',false);return null}var files=Array.from(input.files);var mdFile=files.find(function(f){return /\.md$/i.test(f.name)});if(!mdFile){show('upStatus','文件夹里没找到 .md 文件',false);return null}var mdContent=await mdFile.text();var images=[];for(var i=0;i<files.length;i++){var f=files[i];if(/\.(png|jpe?g|gif|webp|svg|bmp|avif)$/i.test(f.name)){images.push({name:f.name,path:f.webkitRelativePath||f.name,data:await compressImage(f)})}}show('upStatus','正在读入…',true);var d=await api('/api/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:mdFile.name.replace(/\.md$/i,''),content:mdContent,images:images,mdPath:mdFile.webkitRelativePath||mdFile.name})});if(!d.ok){show('upStatus',d.msg||'读入失败',false);return null}document.getElementById('f_content').value=d.content;show('upStatus',d.msg||'已读入',true);return d}
function clearForm(){document.getElementById('up_folder').value='';document.getElementById('f_file').value='';document.getElementById('f_catsave').value='';document.getElementById('f_title').value='';document.getElementById('f_summary').value='';document.getElementById('f_content').value='';document.getElementById('f_newcolname').value='';document.getElementById('f_date').value=nowStr();document.getElementById('form_hd').textContent='发布新文章';document.getElementById('cancelEdit').style.display='none';renderColMenu()}
async function publishPost(){
  var btn=document.getElementById('pubBtn');if(btn)btn.disabled=true;
  try{
    var file=document.getElementById('f_file').value;var hasUp=document.getElementById('up_folder').files.length>0;
    if(hasUp&&file&&!confirm('检测到上传文档，确定替换《'+document.getElementById('f_title').value+'》的正文吗？'))return;
    if(hasUp){var rd=await readFolder();if(!rd)return}
    var title=document.getElementById('f_title').value.trim();if(!title){show('status','请输入标题',false);return}
    var sel=document.getElementById('f_collection');var cat=sel.value;var newcol='';
    if(cat==='__new__'){newcol=document.getElementById('f_newcolname').value.trim();if(!newcol){show('status','请输入新合集名',false);return}cat=newcol;collections.push(cat)}
    var body={file:file,title:title,date:nowStr(),categories:cat,description:document.getElementById('f_summary').value.trim(),content:document.getElementById('f_content').value};
    var d=await api('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});document.getElementById('f_file').value=d.file;
    show('status','正在提交并推送…',true);
    var p=await api('/api/publish',{method:'POST'});
    if(p.ok){clearForm();show('status','已发布并推送',true);function fmtSize(b){b=+b||0;if(b<1024)return b+' B';if(b<1048576)return (b/1024).toFixed(1)+' KB';return (b/1048576).toFixed(2)+' MB'}
function parseExif(buf){var out={};if(!buf||buf.length<4||buf[0]!==0xFF||buf[1]!==0xD8)return out;function u16(o){return (buf[o]<<8)|buf[o+1]}var off=2,tiff=0;while(off+4<buf.length){if(buf[off]!==0xFF){off++;continue}var mar=buf[off+1];var size=u16(off+2);if(mar===0xE1){var sig='';for(var k=0;k<6;k++)sig+=String.fromCharCode(buf[off+4+k]);if(sig==='Exif\0\0'){tiff=off+10;break}}off+=2+size}if(!tiff)return out;var endian=buf.readUInt16BE(tiff);var t=endian===0x4D49?buf.readUInt16LE.bind(buf):buf.readUInt16BE.bind(buf);var t32=endian===0x4D49?buf.readUInt32LE.bind(buf):buf.readUInt32BE.bind(buf);if(endian!==0x4D49&&endian!==0x4949)return out;var ifd0=tiff+t(tiff+2);function rd(dpos,cnt){var s='';for(var j=0;j<cnt;j++)s+=String.fromCharCode(buf[dpos+j]);return s.replace(/\0+$/,'').trim()}function rn(typ,dpos,cnt){return typ===5?(t32(dpos)/t32(dpos+4)).toFixed(1):t(dpos)}function rt(typ,dpos,cnt){if(typ===5){var s2=t32(dpos),d2=t32(dpos+4);if(s2>0&&d2>0){if(s2>=d2)return (s2/d2).toFixed(1)+'s';else return '1/'+Math.round(d2/s2)+'s'}}return t(dpos)}function rtag(ifd){var n=t(ifd),i;for(i=0;i<n;i++){var e=ifd+2+i*12;var tag=t(e),type=t(e+2),cnt=t32(e+4);var valOff=e+8;var bytes=type===1?1:(type===3?2:(type===4?4:type===5?8:type===7?1:4));var size=bytes*cnt;var dp=(size<=4)?valOff:tiff+t32(valOff);if(tag===0x010F)out.Make=rd(dp,cnt);else if(tag===0x0110)out.Model=rd(dp,cnt);else if(tag===0x829D)out.FNumber=rn(type,dp,cnt);else if(tag===0x829A)out.ExposureTime=rt(type,dp,cnt);else if(tag===0x8827)out.ISO=t32(dp);else if(tag===0x920A)out.FocalLength=rn(type,dp,cnt);else if(tag===0xA405)out.FocalLength35=t(dp);else if(tag===0x9209)out.Flash=t(dp);else if(tag===0x9003)out.DateTimeOriginal=rd(dp,cnt);else if(tag===0x8769){var exifIfd=tiff+t32(dp);rtag(exifIfd)}}}rtag(ifd0);return out}
function toNum(s){if(s==null)return NaN;var p=String(s).trim().split('/');if(p.length===2){var n=+p[0],d=+p[1];return d?n/d:NaN}return +p[0]}
function flashStrS(v){v=+v;if(isNaN(v))return '';if(v&1)return '闪光';if(v===0)return '无闪光';if(v===16||v===24)return '未闪光(自动)';if(v===25||v===7)return '闪光(自动)';return (v&1)?'闪光':'未闪光'}
function fmtExifS(ex){if(!ex)return {};var o={};['Make','Model','ISO','DateTimeOriginal'].forEach(function(k){if(ex[k])o[k]=ex[k]});if(ex.FNumber){var fn=toNum(ex.FNumber);if(!isNaN(fn))o.FNumber='f/'+(fn%1?fn.toFixed(1):fn)}if(ex.ExposureTime){var et=String(ex.ExposureTime).trim(),pp=et.split('/');if(pp.length===2){var n=+pp[0],d=+pp[1];if(d&&n>0&&n<d)o.ExposureTime='1/'+Math.round(d/n)+'s';else o.ExposureTime=(n/d).toFixed(1)+'s'}else{var v=+et;if(v>0&&v<1)o.ExposureTime='1/'+Math.round(1/v)+'s';else o.ExposureTime=(v|0)+'s'}}if(ex.FocalLength35){var f35=toNum(ex.FocalLength35);o.FocalLength=((!isNaN(f35))?f35:ex.FocalLength35)+'mm'}else if(ex.FocalLength){var fl=toNum(ex.FocalLength);o.FocalLength=((!isNaN(fl))?fl:ex.FocalLength)+'mm'}if(ex.Flash){var fs=flashStrS(ex.Flash);if(fs)o.Flash=fs}return o}function openImgDetail(src){var lb=document.getElementById('imgdetail'),im=document.getElementById('imgDetailImg');if(!lb||!im)return;lb.classList.add('show');im.src=src;document.body.style.overflow='hidden';document.body.style.paddingRight=(window.innerWidth-document.documentElement.clientWidth)+'px';var info=document.getElementById('imgDetailInfo');info.innerHTML='<div class="imgdetail-loading">读取图片信息…</div>';var tmp=new Image();tmp.onload=function(){var dims=tmp.naturalWidth+' × '+tmp.naturalHeight;fetch(src).then(function(r){return r.arrayBuffer()}).then(function(buf){var ex=parseExif(buf);var size=buf.byteLength;var rows='<div class="imgdetail-rows">';rows+=row('分辨率',dims);rows+=row('文件大小',fmtSize(size));if(ex.DateTimeOriginal)rows+=row('拍摄时间',ex.DateTimeOriginal);rows+='</div>';var fe=fmtExifS(ex);var exr='';['Make','Model','FNumber','ExposureTime','ISO','FocalLength','Flash'].forEach(function(k){if(fe[k])exr+=row({Make:'厂商',Model:'拍摄机型',FNumber:'光圈',ExposureTime:'快门',ISO:'ISO',FocalLength:'焦距',Flash:'闪光灯'}[k],fe[k])});if(fe.DateTimeOriginal)exr+=row('拍摄时间',fe.DateTimeOriginal);info.innerHTML=rows+(exr?'<div class="imgdetail-sub">EXIF</div><div class="imgdetail-rows">'+exr+'</div>':'')}).catch(function(){info.innerHTML='<div class="imgdetail-rows">'+row('分辨率',dims)+'</div>'})};tmp.src=src;function row(k,v){return '<div class="imgdetail-row"><span class="k">'+k+'</span><span class="v">'+v+'</span></div>'}}
function closeImgDetail(){var lb=document.getElementById('imgdetail');if(lb)lb.classList.remove('show');document.body.style.overflow='';document.body.style.paddingRight=''}
document.getElementById('albums').addEventListener('click',function(e){var t=e.target.closest('.imgcard-thumb');if(t&&t.dataset.src){openImgDetail(t.dataset.src)}});load();loadCollections();}
    else{show('status',p.msg||'发布失败',false)}
  }catch(e){show('status','发布出错:'+e.message,false)}
  finally{if(btn)btn.disabled=false}
}
async function delPost(file){if(!confirm('确定删除这篇？'))return;var body={file:file||document.getElementById('f_file').value};await api('/api/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});show('status','已删除',true);load()}

/* ---- 图片（相册） ---- */
var albums=[];
async function loadGallery(){var d=await api('/api/gallery');albums=d.albums||[];renderAlbums()}
var openAlbumIdx=-1;
function renderAlbums(){var el=document.getElementById('albums');el.innerHTML=albums.map(function(a,ai){var isOpen=(openAlbumIdx===ai);var imgCards=(a.images||[]).map(function(im,ii){return '<div class="imgcard"><div class="imgcard-thumb-wrap"><img class="imgcard-thumb" data-src="'+esc(im.src||'')+'" src="'+esc(im.src||'')+'" onerror="this.style.opacity=0"></div><div class="imgcard-body"><div class="imgcard-fields"><input value="'+esc(im.caption||'')+'" placeholder="说明" onchange="albums['+ai+'].images['+ii+'].caption=this.value"><input value="'+esc(im.date||'')+'" placeholder="日期" onchange="albums['+ai+'].images['+ii+'].date=this.value"></div><input class="imgcard-src" value="'+esc(im.src||'')+'" placeholder="/images/…" onchange="albums['+ai+'].images['+ii+'].src=this.value"><button class="btn btn-del btn-block" onclick="delImg('+ai+','+ii+')">删除</button></div></div>'}).join('');return '<div class="album-item"><div class="album-row"><img class="coll-thumb" src="'+esc(a.cover||'')+'" onerror="this.style.opacity=0"><div class="album-row-main"><div class="album-row-name">'+esc(a.name||'')+'</div><div class="album-row-meta">'+(a.images||[]).length+' 张</div></div><div style="display:flex;gap:8px;flex-shrink:0"><button class="btn btn-ghost" onclick="toggleAlbumEdit('+ai+')">'+(isOpen?'收起':'编辑')+'</button><button class="btn btn-del" onclick="delAlbum('+ai+')">删除</button></div></div>'+(isOpen?'<div class="album-edit"><div class="album-edit-grid"><div class="album-edit-cover" onclick="upAlbumCover('+ai+')">'+(a.cover?'<img src="'+esc(a.cover)+'" alt=""><span class="cover-replace">更换封面</span>':'<span class="cover-plus">＋</span><span class="cover-hint">上传封面</span>')+'</div><div class="album-edit-fields"><div class="field"><label>相册名</label><input value="'+esc(a.name||'')+'" onchange="albums['+ai+'].name=this.value"></div><div class="field"><label>简介</label><input value="'+esc(a.desc||'')+'" onchange="albums['+ai+'].desc=this.value"></div></div></div><div class="imgcards">'+imgCards+'</div><div style="margin-top:12px;display:flex;gap:12px;align-items:center"><button class="btn btn-ghost" onclick="addImg('+ai+')">＋ 添加空白</button><label class="btn btn-ghost" style="margin:0;cursor:pointer">上传图片<input type="file" id="galup'+ai+'" accept="image/*" onchange="uploadGalImg('+ai+')" style="display:none"></label></div></div>':'')+'</div>'}).join('')||'<div class="small" style="padding:8px 0">还没有相册</div>'}
function toggleAlbumEdit(i){openAlbumIdx=(openAlbumIdx===i?-1:i);renderAlbums()}function addAlbum(){albums.push({name:'新相册',desc:'',cover:'',images:[]});renderAlbums()}
function upAlbumCover(i){var input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=function(){var f=input.files[0];if(!f)return;compressImage(f).then(function(data){api('/api/img',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({file:f.name,album:'albums',data:data})}).then(function(d){albums[i].cover=d.src;renderAlbums()})})};input.click()}
function delAlbum(i){albums.splice(i,1);renderAlbums()}
function addImg(i){(albums[i].images=albums[i].images||[]).push({caption:'',date:'',src:''});renderAlbums()}
function delImg(i,j){albums[i].images.splice(j,1);renderAlbums()}
async function uploadGalImg(ai){var input=document.getElementById('galup'+ai);var f=input.files[0];if(!f)return;var data=await readAsDataURL(f);var d=await api('/api/img',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({file:f.name,album:albums[ai].name||'misc',data:data})});var dt=new Date(f.lastModified||Date.now());function pad(n){return (n<10?'0':'')+n}var ds=dt.getFullYear()+'-'+pad(dt.getMonth()+1)+'-'+pad(dt.getDate());albums[ai].images.push({caption:f.name.replace(/\.[^.]+$/,''),date:ds,src:d.src});renderAlbums();show('galStatus','已上传 '+d.src,true)}
async function saveGallery(){await api('/api/gallery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({albums:albums})});show('galStatus','已保存图片',true)}

/* ---- 番剧 ---- */
var watching=[];
async function loadWatch(){var d=await api('/api/watching');watching=d.watching||[];renderWatch()}
var pendingMoegirl = {};
function renderWatch(){var el=document.getElementById('watchlist');el.innerHTML=watching.map(function(w,i){return '<div class="wrow"><img class="coll-thumb" src="'+esc(w.cover||'')+'" onerror="this.style.opacity=0"><input value="'+esc(w.title||'')+'" placeholder="番名" onchange="watching['+i+'].title=this.value"><input value="'+esc(w.status||'')+'" placeholder="进度" onchange="watching['+i+'].status=this.value"><input value="'+esc(w.note||'')+'" placeholder="一句话" onchange="watching['+i+'].note=this.value"><button class="btn btn-ghost" onclick="fetchMoegirl('+i+')">抓萌娘</button><button class="btn btn-del" onclick="delWatch('+i+')">删除</button></div>'+(pendingMoegirl[i]?'<div class="wrow-confirm"><img class="coll-thumb" src="'+esc(pendingMoegirl[i].cover||'')+'" onerror="this.style.opacity=0"><div class="wrow-confirm-main"><span>这是《'+esc(pendingMoegirl[i].title||'')+'》吗？</span><div class="wrow-links"><a href="'+esc(pendingMoegirl[i].pageUrl||'#')+'" target="_blank" rel="noopener">打开萌娘页核对</a><a href="'+esc(pendingMoegirl[i].searchUrl||'#')+'" target="_blank" rel="noopener">在萌娘搜索填名字</a></div></div><button class="btn btn-pub" onclick="confirmMoegirl('+i+')">确认保存</button><button class="btn btn-ghost" onclick="rejectMoegirl('+i+')">不是,去填</button></div>':'')}).join('')||'<div class="small" style="padding:8px 0">还没有番剧</div>'}
async function fetchMoegirl(i){var name=watching[i].title||'';if(!name){show('watchStatus','请先填写番名',false);return}show('watchStatus','抓取萌娘百科…',true);try{var d=await api('/api/moegirl?name='+encodeURIComponent(name));pendingMoegirl[i]={title:d.title,cover:d.cover,pageUrl:d.pageUrl,searchUrl:d.searchUrl,found:d.found};show('watchStatus',d.msg||'',true);renderWatch()}catch(e){show('watchStatus','抓取出错',false)}}
function confirmMoegirl(i){var m=pendingMoegirl[i];if(m){watching[i].cover=m.cover;watching[i].title=m.title||watching[i].title;watching[i].pageUrl=m.pageUrl}delete pendingMoegirl[i];saveWatch()}
function rejectMoegirl(i){var m=pendingMoegirl[i];if(m&&m.searchUrl){window.open(m.searchUrl,'_blank')}delete pendingMoegirl[i];renderWatch()}
function addWatch(){watching.push({title:'',status:'',note:'',cover:'',pageUrl:''});renderWatch()}
function delWatch(i){watching.splice(i,1);renderWatch()}
async function saveWatch(){await api('/api/watching',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({watching:watching})});show('watchStatus','已保存番剧',true)}

/* ---- 动态 ---- */
var dynamics=[],editDynIdx=-1;
async function loadDyn(){var d=await api('/api/dynamics');dynamics=d.dynamics||[];renderDyn();resetDyn()}
function renderDyn(){var el=document.getElementById('dynlist');el.innerHTML=dynamics.map(function(d,i){return '<div class="dynrow"><div class="dynrow-main"><div class="dynrow-text">'+esc(d.text||'')+'</div><div class="dynrow-meta">'+esc(d.date||'')+(d.image?' · <span class="dynrow-imgtag">有图</span>':'')+'</div></div><div style="display:flex;gap:6px;align-items:center;flex-shrink:0"><button class="btn btn-ghost" onclick="editDyn('+i+')">编辑</button><button class="btn btn-del" onclick="delDyn('+i+')">删除</button></div></div>'}).join('')||'<div class="small" style="padding:8px 0">还没有动态</div>'}
function resetDyn(){editDynIdx=-1;document.getElementById('dyn_text').value='';document.getElementById('dyn_img').value='';document.getElementById('dyn_date').value=new Date().toISOString().slice(0,10);document.getElementById('dyn_mode').textContent='发布新动态';document.getElementById('dyn_pubbtn').textContent='发布'}
function editDyn(i){editDynIdx=i;var d=dynamics[i];document.getElementById('dyn_text').value=d.text||'';document.getElementById('dyn_img').value=d.image||'';document.getElementById('dyn_date').value=d.date||new Date().toISOString().slice(0,10);document.getElementById('dyn_mode').textContent='编辑动态';document.getElementById('dyn_pubbtn').textContent='更新'}
async function publishDyn(){var text=document.getElementById('dyn_text').value.trim();if(!text){show('dynStatus','请输入内容',false);return}var entry={text:text,image:document.getElementById('dyn_img').value.trim(),date:document.getElementById('dyn_date').value||new Date().toISOString().slice(0,10)};if(editDynIdx>=0){dynamics[editDynIdx]=entry}else{dynamics.unshift(entry)}await saveDyn();resetDyn()}
function upDynCompose(){var input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=function(){var f=input.files[0];if(!f)return;compressImage(f).then(function(data){api('/api/img',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({file:f.name,album:'dynamics',data:data})}).then(function(d){document.getElementById('dyn_img').value=d.src})})};input.click()}
async function saveDyn(){await api('/api/dynamics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dynamics:dynamics})});show('dynStatus','已保存动态',true);renderDyn()}
function delDyn(i){if(!confirm('删除这条动态？'))return;dynamics.splice(i,1);saveDyn()}

/* ---- 首页置顶 ---- */
var allPosts=[],allDyns=[],selPin={};
async function loadPinHome(){var d=await api('/api/posts');allPosts=d.posts||[];var dv=await api('/api/dynamics');allDyns=dv.dynamics||[];var pv=await api('/api/pinned');selPin={};(pv.pinned||[]).forEach(function(it){var key;if(it.type==='post'){key='post:'+allPosts.findIndex(function(p){return p.file===it.file})}else{key='dyn:'+it.index}selPin[key]=true});renderPin()}
function renderPin(){document.getElementById('pin_posts').innerHTML=allPosts.map(function(p,i){return '<div class="pinrow"><input type="checkbox" '+(selPin['post:'+i]?'checked':'')+' onchange="togglePin(\'post:'+i+'\',this)"><span>'+esc(p.title)+'</span></div>'}).join('')||'<div class="small">还没有文章</div>';document.getElementById('pin_dyns').innerHTML=allDyns.map(function(d,i){return '<div class="pinrow"><input type="checkbox" '+(selPin['dyn:'+i]?'checked':'')+' onchange="togglePin(\'dyn:'+i+'\',this)"><span>'+esc(d.text||'')+'</span></div>'}).join('')||'<div class="small">还没有动态</div>';document.getElementById('pinCount').textContent=Object.keys(selPin).length}
function togglePin(key,cb){if(cb.checked){if(Object.keys(selPin).length>=8){cb.checked=false;alert('最多选 8 篇');return}selPin[key]=true}else{delete selPin[key]}document.getElementById('pinCount').textContent=Object.keys(selPin).length}
async function savePin(){var pinned=[];allPosts.forEach(function(p,i){if(selPin['post:'+i])pinned.push({type:'post',file:p.file})});allDyns.forEach(function(d,i){if(selPin['dyn:'+i])pinned.push({type:'dynamic',index:i})});await api('/api/pinned',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pinned:pinned})});show('pinStatus','已保存置顶',true)}

function fmtSize(b){b=+b||0;if(b<1024)return b+' B';if(b<1048576)return (b/1024).toFixed(1)+' KB';return (b/1048576).toFixed(2)+' MB'}
function parseExif(buf){var out={};if(!buf||buf.length<4||buf[0]!==0xFF||buf[1]!==0xD8)return out;function u16(o){return (buf[o]<<8)|buf[o+1]}var off=2,tiff=0;while(off+4<buf.length){if(buf[off]!==0xFF){off++;continue}var mar=buf[off+1];var size=u16(off+2);if(mar===0xE1){var sig='';for(var k=0;k<6;k++)sig+=String.fromCharCode(buf[off+4+k]);if(sig==='Exif\0\0'){tiff=off+10;break}}off+=2+size}if(!tiff)return out;var endian=buf.readUInt16BE(tiff);var t=endian===0x4D49?buf.readUInt16LE.bind(buf):buf.readUInt16BE.bind(buf);var t32=endian===0x4D49?buf.readUInt32LE.bind(buf):buf.readUInt32BE.bind(buf);if(endian!==0x4D49&&endian!==0x4949)return out;var ifd0=tiff+t(tiff+2);function rd(dpos,cnt){var s='';for(var j=0;j<cnt;j++)s+=String.fromCharCode(buf[dpos+j]);return s.replace(/\0+$/,'').trim()}function rn(typ,dpos,cnt){return typ===5?(t32(dpos)/t32(dpos+4)).toFixed(1):t(dpos)}function rt(typ,dpos,cnt){if(typ===5){var s2=t32(dpos),d2=t32(dpos+4);if(s2>0&&d2>0){if(s2>=d2)return (s2/d2).toFixed(1)+'s';else return '1/'+Math.round(d2/s2)+'s'}}return t(dpos)}function rtag(ifd){var n=t(ifd),i;for(i=0;i<n;i++){var e=ifd+2+i*12;var tag=t(e),type=t(e+2),cnt=t32(e+4);var valOff=e+8;var bytes=type===1?1:(type===3?2:(type===4?4:type===5?8:type===7?1:4));var size=bytes*cnt;var dp=(size<=4)?valOff:tiff+t32(valOff);if(tag===0x010F)out.Make=rd(dp,cnt);else if(tag===0x0110)out.Model=rd(dp,cnt);else if(tag===0x829D)out.FNumber=rn(type,dp,cnt);else if(tag===0x829A)out.ExposureTime=rt(type,dp,cnt);else if(tag===0x8827)out.ISO=t32(dp);else if(tag===0x920A)out.FocalLength=rn(type,dp,cnt);else if(tag===0xA405)out.FocalLength35=t(dp);else if(tag===0x9209)out.Flash=t(dp);else if(tag===0x9003)out.DateTimeOriginal=rd(dp,cnt);else if(tag===0x8769){var exifIfd=tiff+t32(dp);rtag(exifIfd)}}}rtag(ifd0);return out}
function toNum(s){if(s==null)return NaN;var p=String(s).trim().split('/');if(p.length===2){var n=+p[0],d=+p[1];return d?n/d:NaN}return +p[0]}
function flashStrS(v){v=+v;if(isNaN(v))return '';if(v&1)return '闪光';if(v===0)return '无闪光';if(v===16||v===24)return '未闪光(自动)';if(v===25||v===7)return '闪光(自动)';return (v&1)?'闪光':'未闪光'}
function fmtExifS(ex){if(!ex)return {};var o={};['Make','Model','ISO','DateTimeOriginal'].forEach(function(k){if(ex[k])o[k]=ex[k]});if(ex.FNumber){var fn=toNum(ex.FNumber);if(!isNaN(fn))o.FNumber='f/'+(fn%1?fn.toFixed(1):fn)}if(ex.ExposureTime){var et=String(ex.ExposureTime).trim(),pp=et.split('/');if(pp.length===2){var n=+pp[0],d=+pp[1];if(d&&n>0&&n<d)o.ExposureTime='1/'+Math.round(d/n)+'s';else o.ExposureTime=(n/d).toFixed(1)+'s'}else{var v=+et;if(v>0&&v<1)o.ExposureTime='1/'+Math.round(1/v)+'s';else o.ExposureTime=(v|0)+'s'}}if(ex.FocalLength35){var f35=toNum(ex.FocalLength35);o.FocalLength=((!isNaN(f35))?f35:ex.FocalLength35)+'mm'}else if(ex.FocalLength){var fl=toNum(ex.FocalLength);o.FocalLength=((!isNaN(fl))?fl:ex.FocalLength)+'mm'}if(ex.Flash){var fs=flashStrS(ex.Flash);if(fs)o.Flash=fs}return o}function openImgDetail(src){var lb=document.getElementById('imgdetail'),im=document.getElementById('imgDetailImg');if(!lb||!im)return;lb.classList.add('show');im.src=src;document.body.style.overflow='hidden';document.body.style.paddingRight=(window.innerWidth-document.documentElement.clientWidth)+'px';var info=document.getElementById('imgDetailInfo');info.innerHTML='<div class="imgdetail-loading">读取图片信息…</div>';var tmp=new Image();tmp.onload=function(){var dims=tmp.naturalWidth+' × '+tmp.naturalHeight;fetch(src).then(function(r){return r.arrayBuffer()}).then(function(buf){var ex=parseExif(buf);var size=buf.byteLength;var rows='<div class="imgdetail-rows">';rows+=row('分辨率',dims);rows+=row('文件大小',fmtSize(size));if(ex.DateTimeOriginal)rows+=row('拍摄时间',ex.DateTimeOriginal);rows+='</div>';var fe=fmtExifS(ex);var exr='';['Make','Model','FNumber','ExposureTime','ISO','FocalLength','Flash'].forEach(function(k){if(fe[k])exr+=row({Make:'厂商',Model:'拍摄机型',FNumber:'光圈',ExposureTime:'快门',ISO:'ISO',FocalLength:'焦距',Flash:'闪光灯'}[k],fe[k])});if(fe.DateTimeOriginal)exr+=row('拍摄时间',fe.DateTimeOriginal);info.innerHTML=rows+(exr?'<div class="imgdetail-sub">EXIF</div><div class="imgdetail-rows">'+exr+'</div>':'')}).catch(function(){info.innerHTML='<div class="imgdetail-rows">'+row('分辨率',dims)+'</div>'})};tmp.src=src;function row(k,v){return '<div class="imgdetail-row"><span class="k">'+k+'</span><span class="v">'+v+'</span></div>'}}
function closeImgDetail(){var lb=document.getElementById('imgdetail');if(lb)lb.classList.remove('show');document.body.style.overflow='';document.body.style.paddingRight=''}
document.getElementById('albums').addEventListener('click',function(e){var t=e.target.closest('.imgcard-thumb');if(t&&t.dataset.src){openImgDetail(t.dataset.src)}});load();loadCollections();loadGallery();loadWatch();loadDyn();loadPinHome();
